print("Getting to know you!")
yourName = input("what is your name?")
yourfood = input("your favourite food is?")
yourMusic = input("what is your favourite music?")
yourHome = input("where do you live?")
print()
print("you are")
print(yourName)
print("you said your fav food is")
print(yourfood)
print("and you are getting your moods up with")
print(yourMusic)
print("living is the most populated city in africa")
print(yourHome)
print("thank you for the information!")